language: go

python:
  - 3.8

go_import_path: autograder

services:
  - docker

before_install:
  - pip install -U pytest --user

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"
  - pip install -r marker/requirements.txt --user

script:
  - make build
  - pytest


