matrix:
  include:

    -
      language: go

      go_import_path: autograder

      services:
        - docker
        - redis

#      before_script:
#        - sudo redis-server --port 6379

      install:
        - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
        - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

      script:
        - make build

    -
      language: python

      python:
        - 3.7.1

      before_install:
        - pip install -U pytest
        - pip install -r "${TRAVIS_BUILD_DIR}/marker/requirements.txt"

      script:
        - pytest
