
matrix:
  include:

    -
    language: go

        go_import_path: autograder

        services:
          - docker

        install:
          - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
          - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

        script:
          - make build

  -
    language: python

    python:
      - 3.7.1

    before_install:
      - pip install -U pytest --user
      - pip install -r "${TRAVIS_BUILD_DIR}/marker/requirements.txt" --user

    script:
      - pytest