language: go

python:
  - 3.8

go_import_path: autograder

services:
  - docker

before_install:
  - pip3 install -U pytest --user
  - pip3 install -r "${TRAVIS_BUILD_DIR}/marker/requirements.txt" --user

install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace:$GOPATH"
  - export PATH="${TRAVIS_BUILD_DIR}/Godeps/_workspace/bin:$PATH"

script:
  - make build
  - pytest


