base_dir: ./templates/
dockerfile_path: marker/Dockerfile
host: "0.0.0.0"
labs:
  -
    id: lab_1
    name: Lab 1 - Hello world Program
    problem_statement: Write a program in python that prints "Hello World"\nmake sure you have the correct spelling
    testcase:
      -
        expected:
          -
            feedback: "Correct!"
            points: 1.0
            values:
              - "Hello World"
              - "hello world"
              - "Hello world"
              - "hello world"
        type: stdout
  -
    id: lab_2
    name: Lab 2 - Pythogrean Theorm
    problem_statement: |
      Write a function called pythgoeran(a,b) that takes 2 inputs a, and b which are 2 sides of a
      right angle triangle \n returns the hypotenuse c of the triangle

    testcase:
      -
        type: function
        input:
          - 3
          - 4
        expected:
          -
            feedback: Nice
            points: 1.0
            values:
              - 5.0



log_dir: logs/
read_timeout: 5
redis:
  max_retry: 3
  rate_limiter: 50-H
  redis_server: "redis://0.0.0.0:6379"
server_port: 9090
template_path: ./templates
test_case_path: ./test_cases/
write_timeout: 5
