base_dir: ./templates/
dockerfile_path: marker/Dockerfile
host: "0.0.0.0"
labs:
  -
    name: lab_1
    testcase:
      -
        expected:
          -
            feedback: "this is the wrong anwser"
            points: 0.5
            values:
              - "1"
              - "2.6"
        type: stdout
log_dir: logs/
read_timeout: 5
redis:
  max_retry: 3
  rate_limiter: 50-H
  redis_server: "redis://0.0.0.0:6379"
server_port: 9090
template_path: ./templates
test_case_path: ./test_cases/
write_timeout: 5
