version: "2"

services:
    goserver:
        build: .
        ports:
            - 9090:9090
        volumes:
            - .:/go/
    
    
    redis:
        container_name: redis
        image: redis
        ports:
            - "6379:6379"
 