// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package models

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

/// Lab assignment exposed via GET /api/labs.
type LabT struct {
	Id string `json:"id"`
	Name string `json:"name"`
	ProblemStatement string `json:"problem_statement"`
}

func (t *LabT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	idOffset := flatbuffers.UOffsetT(0)
	if t.Id != "" {
		idOffset = builder.CreateString(t.Id)
	}
	nameOffset := flatbuffers.UOffsetT(0)
	if t.Name != "" {
		nameOffset = builder.CreateString(t.Name)
	}
	problemStatementOffset := flatbuffers.UOffsetT(0)
	if t.ProblemStatement != "" {
		problemStatementOffset = builder.CreateString(t.ProblemStatement)
	}
	LabStart(builder)
	LabAddId(builder, idOffset)
	LabAddName(builder, nameOffset)
	LabAddProblemStatement(builder, problemStatementOffset)
	return LabEnd(builder)
}

func (rcv *Lab) UnPackTo(t *LabT) {
	t.Id = string(rcv.Id())
	t.Name = string(rcv.Name())
	t.ProblemStatement = string(rcv.ProblemStatement())
}

func (rcv *Lab) UnPack() *LabT {
	if rcv == nil {
		return nil
	}
	t := &LabT{}
	rcv.UnPackTo(t)
	return t
}

type Lab struct {
	_tab flatbuffers.Table
}

func GetRootAsLab(buf []byte, offset flatbuffers.UOffsetT) *Lab {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Lab{}
	x.Init(buf, n+offset)
	return x
}

func FinishLabBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsLab(buf []byte, offset flatbuffers.UOffsetT) *Lab {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Lab{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedLabBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Lab) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Lab) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Lab) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Lab) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Lab) ProblemStatement() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func LabStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func LabAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func LabAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func LabAddProblemStatement(builder *flatbuffers.Builder, problemStatement flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(problemStatement), 0)
}
func LabEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
/// Grading result for a single test case.
type EvaluationT struct {
	Type string `json:"type"`
	Name string `json:"name"`
	Actual string `json:"actual"`
	Status string `json:"status"`
	Points float32 `json:"points"`
}

func (t *EvaluationT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	type_Offset := flatbuffers.UOffsetT(0)
	if t.Type != "" {
		type_Offset = builder.CreateString(t.Type)
	}
	nameOffset := flatbuffers.UOffsetT(0)
	if t.Name != "" {
		nameOffset = builder.CreateString(t.Name)
	}
	actualOffset := flatbuffers.UOffsetT(0)
	if t.Actual != "" {
		actualOffset = builder.CreateString(t.Actual)
	}
	statusOffset := flatbuffers.UOffsetT(0)
	if t.Status != "" {
		statusOffset = builder.CreateString(t.Status)
	}
	EvaluationStart(builder)
	EvaluationAddType(builder, type_Offset)
	EvaluationAddName(builder, nameOffset)
	EvaluationAddActual(builder, actualOffset)
	EvaluationAddStatus(builder, statusOffset)
	EvaluationAddPoints(builder, t.Points)
	return EvaluationEnd(builder)
}

func (rcv *Evaluation) UnPackTo(t *EvaluationT) {
	t.Type = string(rcv.Type())
	t.Name = string(rcv.Name())
	t.Actual = string(rcv.Actual())
	t.Status = string(rcv.Status())
	t.Points = rcv.Points()
}

func (rcv *Evaluation) UnPack() *EvaluationT {
	if rcv == nil {
		return nil
	}
	t := &EvaluationT{}
	rcv.UnPackTo(t)
	return t
}

type Evaluation struct {
	_tab flatbuffers.Table
}

func GetRootAsEvaluation(buf []byte, offset flatbuffers.UOffsetT) *Evaluation {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Evaluation{}
	x.Init(buf, n+offset)
	return x
}

func FinishEvaluationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEvaluation(buf []byte, offset flatbuffers.UOffsetT) *Evaluation {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Evaluation{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEvaluationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Evaluation) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Evaluation) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Evaluation) Type() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Evaluation) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Evaluation) Actual() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Evaluation) Status() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Evaluation) Points() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Evaluation) MutatePoints(n float32) bool {
	return rcv._tab.MutateFloat32Slot(12, n)
}

func EvaluationStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func EvaluationAddType(builder *flatbuffers.Builder, type_ flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(type_), 0)
}
func EvaluationAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func EvaluationAddActual(builder *flatbuffers.Builder, actual flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(actual), 0)
}
func EvaluationAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(status), 0)
}
func EvaluationAddPoints(builder *flatbuffers.Builder, points float32) {
	builder.PrependFloat32Slot(4, points, 0.0)
}
func EvaluationEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
/// Full grading result returned by POST /api/submit.
type GradeResultT struct {
	Evaluations []*EvaluationT `json:"evaluations"`
	TotalPoints float32 `json:"total_points"`
}

func (t *GradeResultT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	evaluationsOffset := flatbuffers.UOffsetT(0)
	if t.Evaluations != nil {
		evaluationsLength := len(t.Evaluations)
		evaluationsOffsets := make([]flatbuffers.UOffsetT, evaluationsLength)
		for j := 0; j < evaluationsLength; j++ {
			evaluationsOffsets[j] = t.Evaluations[j].Pack(builder)
		}
		GradeResultStartEvaluationsVector(builder, evaluationsLength)
		for j := evaluationsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(evaluationsOffsets[j])
		}
		evaluationsOffset = builder.EndVector(evaluationsLength)
	}
	GradeResultStart(builder)
	GradeResultAddEvaluations(builder, evaluationsOffset)
	GradeResultAddTotalPoints(builder, t.TotalPoints)
	return GradeResultEnd(builder)
}

func (rcv *GradeResult) UnPackTo(t *GradeResultT) {
	evaluationsLength := rcv.EvaluationsLength()
	t.Evaluations = make([]*EvaluationT, evaluationsLength)
	for j := 0; j < evaluationsLength; j++ {
		x := Evaluation{}
		rcv.Evaluations(&x, j)
		t.Evaluations[j] = x.UnPack()
	}
	t.TotalPoints = rcv.TotalPoints()
}

func (rcv *GradeResult) UnPack() *GradeResultT {
	if rcv == nil {
		return nil
	}
	t := &GradeResultT{}
	rcv.UnPackTo(t)
	return t
}

type GradeResult struct {
	_tab flatbuffers.Table
}

func GetRootAsGradeResult(buf []byte, offset flatbuffers.UOffsetT) *GradeResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GradeResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishGradeResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGradeResult(buf []byte, offset flatbuffers.UOffsetT) *GradeResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GradeResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGradeResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GradeResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GradeResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GradeResult) Evaluations(obj *Evaluation, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *GradeResult) EvaluationsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GradeResult) TotalPoints() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *GradeResult) MutateTotalPoints(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func GradeResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GradeResultAddEvaluations(builder *flatbuffers.Builder, evaluations flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(evaluations), 0)
}
func GradeResultStartEvaluationsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GradeResultAddTotalPoints(builder *flatbuffers.Builder, totalPoints float32) {
	builder.PrependFloat32Slot(1, totalPoints, 0.0)
}
func GradeResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
/// Standard API error response.
type APIErrorT struct {
	Error string `json:"error"`
}

func (t *APIErrorT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	errorOffset := flatbuffers.UOffsetT(0)
	if t.Error != "" {
		errorOffset = builder.CreateString(t.Error)
	}
	APIErrorStart(builder)
	APIErrorAddError(builder, errorOffset)
	return APIErrorEnd(builder)
}

func (rcv *APIError) UnPackTo(t *APIErrorT) {
	t.Error = string(rcv.Error())
}

func (rcv *APIError) UnPack() *APIErrorT {
	if rcv == nil {
		return nil
	}
	t := &APIErrorT{}
	rcv.UnPackTo(t)
	return t
}

type APIError struct {
	_tab flatbuffers.Table
}

func GetRootAsAPIError(buf []byte, offset flatbuffers.UOffsetT) *APIError {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &APIError{}
	x.Init(buf, n+offset)
	return x
}

func FinishAPIErrorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAPIError(buf []byte, offset flatbuffers.UOffsetT) *APIError {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &APIError{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAPIErrorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *APIError) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *APIError) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *APIError) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func APIErrorStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func APIErrorAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(error), 0)
}
func APIErrorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
/// Typed argument for a function call.
type FunctionArgT struct {
	Type string `json:"type"`
	Value string `json:"value"`
}

func (t *FunctionArgT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	type_Offset := flatbuffers.UOffsetT(0)
	if t.Type != "" {
		type_Offset = builder.CreateString(t.Type)
	}
	valueOffset := flatbuffers.UOffsetT(0)
	if t.Value != "" {
		valueOffset = builder.CreateString(t.Value)
	}
	FunctionArgStart(builder)
	FunctionArgAddType(builder, type_Offset)
	FunctionArgAddValue(builder, valueOffset)
	return FunctionArgEnd(builder)
}

func (rcv *FunctionArg) UnPackTo(t *FunctionArgT) {
	t.Type = string(rcv.Type())
	t.Value = string(rcv.Value())
}

func (rcv *FunctionArg) UnPack() *FunctionArgT {
	if rcv == nil {
		return nil
	}
	t := &FunctionArgT{}
	rcv.UnPackTo(t)
	return t
}

type FunctionArg struct {
	_tab flatbuffers.Table
}

func GetRootAsFunctionArg(buf []byte, offset flatbuffers.UOffsetT) *FunctionArg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FunctionArg{}
	x.Init(buf, n+offset)
	return x
}

func FinishFunctionArgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFunctionArg(buf []byte, offset flatbuffers.UOffsetT) *FunctionArg {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FunctionArg{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFunctionArgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FunctionArg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FunctionArg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FunctionArg) Type() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FunctionArg) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func FunctionArgStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func FunctionArgAddType(builder *flatbuffers.Builder, type_ flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(type_), 0)
}
func FunctionArgAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func FunctionArgEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
/// Function call to be tested.
type FunctionT struct {
	FunctionName string `json:"function_name"`
	FunctionArgs []*FunctionArgT `json:"function_args"`
	TestcaseName string `json:"testcase_name"`
}

func (t *FunctionT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	functionNameOffset := flatbuffers.UOffsetT(0)
	if t.FunctionName != "" {
		functionNameOffset = builder.CreateString(t.FunctionName)
	}
	functionArgsOffset := flatbuffers.UOffsetT(0)
	if t.FunctionArgs != nil {
		functionArgsLength := len(t.FunctionArgs)
		functionArgsOffsets := make([]flatbuffers.UOffsetT, functionArgsLength)
		for j := 0; j < functionArgsLength; j++ {
			functionArgsOffsets[j] = t.FunctionArgs[j].Pack(builder)
		}
		FunctionStartFunctionArgsVector(builder, functionArgsLength)
		for j := functionArgsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(functionArgsOffsets[j])
		}
		functionArgsOffset = builder.EndVector(functionArgsLength)
	}
	testcaseNameOffset := flatbuffers.UOffsetT(0)
	if t.TestcaseName != "" {
		testcaseNameOffset = builder.CreateString(t.TestcaseName)
	}
	FunctionStart(builder)
	FunctionAddFunctionName(builder, functionNameOffset)
	FunctionAddFunctionArgs(builder, functionArgsOffset)
	FunctionAddTestcaseName(builder, testcaseNameOffset)
	return FunctionEnd(builder)
}

func (rcv *Function) UnPackTo(t *FunctionT) {
	t.FunctionName = string(rcv.FunctionName())
	functionArgsLength := rcv.FunctionArgsLength()
	t.FunctionArgs = make([]*FunctionArgT, functionArgsLength)
	for j := 0; j < functionArgsLength; j++ {
		x := FunctionArg{}
		rcv.FunctionArgs(&x, j)
		t.FunctionArgs[j] = x.UnPack()
	}
	t.TestcaseName = string(rcv.TestcaseName())
}

func (rcv *Function) UnPack() *FunctionT {
	if rcv == nil {
		return nil
	}
	t := &FunctionT{}
	rcv.UnPackTo(t)
	return t
}

type Function struct {
	_tab flatbuffers.Table
}

func GetRootAsFunction(buf []byte, offset flatbuffers.UOffsetT) *Function {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Function{}
	x.Init(buf, n+offset)
	return x
}

func FinishFunctionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFunction(buf []byte, offset flatbuffers.UOffsetT) *Function {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Function{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFunctionBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Function) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Function) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Function) FunctionName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Function) FunctionArgs(obj *FunctionArg, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Function) FunctionArgsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *Function) TestcaseName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func FunctionStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func FunctionAddFunctionName(builder *flatbuffers.Builder, functionName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(functionName), 0)
}
func FunctionAddFunctionArgs(builder *flatbuffers.Builder, functionArgs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(functionArgs), 0)
}
func FunctionStartFunctionArgsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func FunctionAddTestcaseName(builder *flatbuffers.Builder, testcaseName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(testcaseName), 0)
}
func FunctionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
/// JSON payload sent to the marker container.
type MarkerInputT struct {
	Filename string `json:"filename"`
	Stdout bool `json:"stdout"`
	Functions []*FunctionT `json:"functions"`
}

func (t *MarkerInputT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	filenameOffset := flatbuffers.UOffsetT(0)
	if t.Filename != "" {
		filenameOffset = builder.CreateString(t.Filename)
	}
	functionsOffset := flatbuffers.UOffsetT(0)
	if t.Functions != nil {
		functionsLength := len(t.Functions)
		functionsOffsets := make([]flatbuffers.UOffsetT, functionsLength)
		for j := 0; j < functionsLength; j++ {
			functionsOffsets[j] = t.Functions[j].Pack(builder)
		}
		MarkerInputStartFunctionsVector(builder, functionsLength)
		for j := functionsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(functionsOffsets[j])
		}
		functionsOffset = builder.EndVector(functionsLength)
	}
	MarkerInputStart(builder)
	MarkerInputAddFilename(builder, filenameOffset)
	MarkerInputAddStdout(builder, t.Stdout)
	MarkerInputAddFunctions(builder, functionsOffset)
	return MarkerInputEnd(builder)
}

func (rcv *MarkerInput) UnPackTo(t *MarkerInputT) {
	t.Filename = string(rcv.Filename())
	t.Stdout = rcv.Stdout()
	functionsLength := rcv.FunctionsLength()
	t.Functions = make([]*FunctionT, functionsLength)
	for j := 0; j < functionsLength; j++ {
		x := Function{}
		rcv.Functions(&x, j)
		t.Functions[j] = x.UnPack()
	}
}

func (rcv *MarkerInput) UnPack() *MarkerInputT {
	if rcv == nil {
		return nil
	}
	t := &MarkerInputT{}
	rcv.UnPackTo(t)
	return t
}

type MarkerInput struct {
	_tab flatbuffers.Table
}

func GetRootAsMarkerInput(buf []byte, offset flatbuffers.UOffsetT) *MarkerInput {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MarkerInput{}
	x.Init(buf, n+offset)
	return x
}

func FinishMarkerInputBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMarkerInput(buf []byte, offset flatbuffers.UOffsetT) *MarkerInput {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MarkerInput{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMarkerInputBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MarkerInput) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MarkerInput) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MarkerInput) Filename() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MarkerInput) Stdout() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *MarkerInput) MutateStdout(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *MarkerInput) Functions(obj *Function, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MarkerInput) FunctionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func MarkerInputStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MarkerInputAddFilename(builder *flatbuffers.Builder, filename flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(filename), 0)
}
func MarkerInputAddStdout(builder *flatbuffers.Builder, stdout bool) {
	builder.PrependBoolSlot(1, stdout, false)
}
func MarkerInputAddFunctions(builder *flatbuffers.Builder, functions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(functions), 0)
}
func MarkerInputStartFunctionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MarkerInputEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
/// Single function's output from the marker.
type FunctionResultT struct {
	Result string `json:"result"`
	Status int32 `json:"status"`
	Buffer string `json:"buffer"`
	TestcaseName string `json:"testcase_name"`
}

func (t *FunctionResultT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	resultOffset := flatbuffers.UOffsetT(0)
	if t.Result != "" {
		resultOffset = builder.CreateString(t.Result)
	}
	bufferOffset := flatbuffers.UOffsetT(0)
	if t.Buffer != "" {
		bufferOffset = builder.CreateString(t.Buffer)
	}
	testcaseNameOffset := flatbuffers.UOffsetT(0)
	if t.TestcaseName != "" {
		testcaseNameOffset = builder.CreateString(t.TestcaseName)
	}
	FunctionResultStart(builder)
	FunctionResultAddResult(builder, resultOffset)
	FunctionResultAddStatus(builder, t.Status)
	FunctionResultAddBuffer(builder, bufferOffset)
	FunctionResultAddTestcaseName(builder, testcaseNameOffset)
	return FunctionResultEnd(builder)
}

func (rcv *FunctionResult) UnPackTo(t *FunctionResultT) {
	t.Result = string(rcv.Result())
	t.Status = rcv.Status()
	t.Buffer = string(rcv.Buffer())
	t.TestcaseName = string(rcv.TestcaseName())
}

func (rcv *FunctionResult) UnPack() *FunctionResultT {
	if rcv == nil {
		return nil
	}
	t := &FunctionResultT{}
	rcv.UnPackTo(t)
	return t
}

type FunctionResult struct {
	_tab flatbuffers.Table
}

func GetRootAsFunctionResult(buf []byte, offset flatbuffers.UOffsetT) *FunctionResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FunctionResult{}
	x.Init(buf, n+offset)
	return x
}

func FinishFunctionResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFunctionResult(buf []byte, offset flatbuffers.UOffsetT) *FunctionResult {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FunctionResult{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFunctionResultBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FunctionResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FunctionResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FunctionResult) Result() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FunctionResult) Status() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FunctionResult) MutateStatus(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func (rcv *FunctionResult) Buffer() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *FunctionResult) TestcaseName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func FunctionResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func FunctionResultAddResult(builder *flatbuffers.Builder, result flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(result), 0)
}
func FunctionResultAddStatus(builder *flatbuffers.Builder, status int32) {
	builder.PrependInt32Slot(1, status, 0)
}
func FunctionResultAddBuffer(builder *flatbuffers.Builder, buffer flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(buffer), 0)
}
func FunctionResultAddTestcaseName(builder *flatbuffers.Builder, testcaseName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(testcaseName), 0)
}
func FunctionResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
/// JSON result from the marker container.
type MarkerOutputT struct {
	Stdout string `json:"stdout"`
	Functions []*FunctionResultT `json:"functions"`
}

func (t *MarkerOutputT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	stdoutOffset := flatbuffers.UOffsetT(0)
	if t.Stdout != "" {
		stdoutOffset = builder.CreateString(t.Stdout)
	}
	functionsOffset := flatbuffers.UOffsetT(0)
	if t.Functions != nil {
		functionsLength := len(t.Functions)
		functionsOffsets := make([]flatbuffers.UOffsetT, functionsLength)
		for j := 0; j < functionsLength; j++ {
			functionsOffsets[j] = t.Functions[j].Pack(builder)
		}
		MarkerOutputStartFunctionsVector(builder, functionsLength)
		for j := functionsLength - 1; j >= 0; j-- {
			builder.PrependUOffsetT(functionsOffsets[j])
		}
		functionsOffset = builder.EndVector(functionsLength)
	}
	MarkerOutputStart(builder)
	MarkerOutputAddStdout(builder, stdoutOffset)
	MarkerOutputAddFunctions(builder, functionsOffset)
	return MarkerOutputEnd(builder)
}

func (rcv *MarkerOutput) UnPackTo(t *MarkerOutputT) {
	t.Stdout = string(rcv.Stdout())
	functionsLength := rcv.FunctionsLength()
	t.Functions = make([]*FunctionResultT, functionsLength)
	for j := 0; j < functionsLength; j++ {
		x := FunctionResult{}
		rcv.Functions(&x, j)
		t.Functions[j] = x.UnPack()
	}
}

func (rcv *MarkerOutput) UnPack() *MarkerOutputT {
	if rcv == nil {
		return nil
	}
	t := &MarkerOutputT{}
	rcv.UnPackTo(t)
	return t
}

type MarkerOutput struct {
	_tab flatbuffers.Table
}

func GetRootAsMarkerOutput(buf []byte, offset flatbuffers.UOffsetT) *MarkerOutput {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MarkerOutput{}
	x.Init(buf, n+offset)
	return x
}

func FinishMarkerOutputBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMarkerOutput(buf []byte, offset flatbuffers.UOffsetT) *MarkerOutput {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MarkerOutput{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMarkerOutputBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MarkerOutput) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MarkerOutput) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MarkerOutput) Stdout() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MarkerOutput) Functions(obj *FunctionResult, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MarkerOutput) FunctionsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func MarkerOutputStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MarkerOutputAddStdout(builder *flatbuffers.Builder, stdout flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(stdout), 0)
}
func MarkerOutputAddFunctions(builder *flatbuffers.Builder, functions flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(functions), 0)
}
func MarkerOutputStartFunctionsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MarkerOutputEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
